server:
  port: 8080

spring:
  application:
    name: SpringCRUD
  data:
    mongodb:
      host: localhost
      port: 27017
      database: StudentDB
  jackson:
    default-property-inclusion: NON_NULL
    

